import Head from "next/head";
import Image from "next/image";
import GridGallery from "../components/grid-gallery";

export default function Home() {
  const images = [
    "./mountains.jpg",
    "./mountains.jpg",
    "./mountains.jpg",
    "./mountains.jpg",
    "./mountains.jpg",
    "./mountains.jpg",
    "./mountains.jpg",
    "./mountains.jpg",
    "./mountains.jpg",
    "./mountains.jpg",
    "./mountains.jpg",
    "./mountains.jpg",
    "./mountains.jpg",
    "./mountains.jpg",
  ];
  return (
    <>
      <Head>
        <title>Grid Gallery</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='mx-auto bg-gray-800 p-8'>
        <h1 className='text-2xl md:text-6xl sm:text-4xl lg:text-8xl text-white text-center mb-10 '>
          Front-End Test
        </h1>
        <div className='mx-auto w-9/12'>
          <GridGallery images={images} />
        </div>
      </div>
    </>
  );
}
